"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _overview_subtitle from './overview-subtitle.bones.json'
import _summary_metrics from './summary-metrics.bones.json'
import _chart_allocation from './chart-allocation.bones.json'
import _chart_invested_value from './chart-invested-value.bones.json'
import _chart_gainloss from './chart-gainloss.bones.json'
import _chart_top_holdings from './chart-top-holdings.bones.json'
import _sector_summary from './sector-summary.bones.json'
import _holdings_table from './holdings-table.bones.json'

registerBones({
  "overview-subtitle": _overview_subtitle,
  "summary-metrics": _summary_metrics,
  "chart-allocation": _chart_allocation,
  "chart-invested-value": _chart_invested_value,
  "chart-gainloss": _chart_gainloss,
  "chart-top-holdings": _chart_top_holdings,
  "sector-summary": _sector_summary,
  "holdings-table": _holdings_table,
})
