"use client";

import type { ReactNode } from "react";
import { Skeleton } from "boneyard-js/react";

// App-level boneyard defaults so sections don't repeat them; bones are
// generated by `npx boneyard-js build` and registered in app/layout.tsx.
const boneDefaults = {
  color: "#e6e9ef",
  darkColor: "#2a2f3a",
  animate: "shimmer" as const,
  transition: 250,
};

export function Bone({
  name,
  loading,
  className,
  children,
}: {
  name: string;
  loading: boolean;
  className?: string;
  children: ReactNode;
}) {
  return (
    <Skeleton name={name} loading={loading} className={className} {...boneDefaults}>
      {children}
    </Skeleton>
  );
}
